### ISSUE TITLE
前缀树中有一些问题需要

### ISSUE THREAD

**Issue by liu6zijian** [WangXFng/TrieLLM#1]
您好，我有一些TrieLLM的代码不明白需要向您请教一下
1. 首先，"next token is :"，其中":"是last token，那么self.last_token = tokenizer(last_token)['input_ids'][1:][0]中，它已经是最后一个，切片索引[1:]就没有了
<img width="824" alt="image" src="https://github.com/user-attachments/assets/f121bde8-ff5b-4a0e-9dc0-e413d6b767cf">
我暂时改成了 self.last_token = tokenizer(last_token)['input_ids'][0]
2. 其次，__call__()中的迭代没有很理解，我得出的结果是两个相同的序列
<img width="438" alt="image" src="https://github.com/user-attachments/assets/5c1f98fd-dc26-4d1c-a385-6eb24fc37dd2">
这里需要比较num_beam的分数吗？还是应该怎么处理。感激

**Comment by WangXFng** [comment]
请说哈

**Comment by liu6zijian** [comment]
已附上问题，感谢

**Comment by WangXFng** [comment]
这个[1:]是因为Llama3.2-1B默认会在前面加上一个“< s>”字符对应的ID表示句子开始的地方。如果你换了基座模型的话，确实可能要改一下逻辑。

你可以在解码前把output_ids 打印出来看看是不是完全一样的。按我理解是不应该一样的，比如有个空格什么的。这个__call__的话，应该就是在选词前会被调用一遍。

另外，我在Llama3.2-1B上测试过。比较beam search分数的时候，它不会输出一样的序列的。即使分数都是负无穷的话，他会从ID为0的token开始从小到大取，生成不一样的序列出来。

**Comment by liu6zijian** [comment]
----- 原始邮件 -----
发件人：Xinfeng Wang ***@***.***>
收件人：WangXFng/TrieLLM ***@***.***>
抄送人：liu6zijian ***@***.***>,  Author ***@***.***>
主题：Re:_[WangXFng/TrieLLM]_前缀树中有一些问题需要_(Issue_#1)
日期：2024年10月21日 20点41分


这个[1:]是因为Llama3.2-1B默认会在前面加上一个字符对应的ID表示句子开始的地方。如果你换了基座模型的话，确实可能要改一下逻辑。

你可以在解码前把output_ids 打印出来看看是不是完全一样的。按我理解是不应该一样的。

如果还有问题你可以邮箱发我代码，我来看看

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.
您好，我的代码是这样修改的。国内没有llama的token id，暂用的qwen2.5-1.5b做尝试。我打印了一下outputs_ids，两行也是一样的。还得麻烦您帮忙看一下，感谢Message ID: ***@***.***>

**Comment by WangXFng** [comment]
稍等我去申请一个qwen的token

**Comment by WangXFng** [comment]
我新建了一个qwen1.5分支，你pull一下。我跑起来生成是不一样的序列额。你试试

**Comment by liu6zijian** [comment]
非常感谢，问题已解决
